### ISSUE TITLE
Best way to send an image/attachment via the browser?

### ISSUE THREAD

**Issue by averyvery** [smooch/smooch-core-js#89]
Been digging into this for a few hours now, and I'm not sure what the recommended way to upload a file to smooch + attach it to a message via the browser is at the moment. I'm using 4.3.0, and initing with `const api = new SmoochCore({ appToken: smoochAppToken });`

I have a coworking who's working with smooch via the iOS SDK, and he's able to upload 7mb images and send them as messages, but I can't seem to do the same thing over the web, so I'm wondering if I'm doing something wrong or if requests from the web just have a filesize restriction.

- Older docs recommended using `appUsers.uploadImage`, but throws request entity size errors for files over ~2mb
- POSTing directly to `https://api.smooch.io/v1/appusers/${this.userId}/images` with a source of the file, a role of 'appUser' and an `app-token` header, produces the same result — "entity too large" errors. This is the exact route our iOS library is hitting, with the same files, but it doesn't seem to get any errors.
- There doesn't seem to be a an `attachments` object on the api (this is mentioned in the readme, but it's undefined on the SmoochCore instance itself) that I can use.
- POSTing to (what looks like) attachments with the following code throws a 401 (unauthorized) error.

```
    const body = new FormData();
    body.append('source', image);

    axios.post(`https://api.smooch.io/v1/apps/${smoochAppId}/attachments?access=public`,
      body,
      {
        headers: {
          'app-token': smoochAppToken,
        },
      },
    )
```

---

I guess, in summary, my questions are:

- What is the current, recommended method for sending a file via the API with this lib?
- Is there a reason you can think of that an iOS API consumer would be able to send larger files without issue?

**Comment by jugarrit** [comment]
> What is the current, recommended method for sending a file via the API with this lib?

To send a file via the API, you need to be authenticated with an app JWT, which brings me to the next question...

> There doesn't seem to be a an attachments object on the api (this is mentioned in the readme, but it's undefined on the SmoochCore instance itself) that I can use.

When you instantiate SmoochCore with an `appToken`, only the APIs that are accessible via `appToken` are exposed on the resulting object. Anything else would result in 401 anyways.

> Is there a reason you can think of that an iOS API consumer would be able to send larger files without issue?

The iOS SDK actually resizes the image before sending it to the `/images` API. That's why it's able to send larger files. You could attempt a similar method before attempting the upload via the browser, but note that you will be limited to uploading images only.

For an example of what this would look like, you can take a look at [our implementation](https://github.com/smooch/smooch-js/blob/bd1b5d2aa6b3db833bf75717c726d2eb166242cf/src/js/utils/media.js#L34) in `smooch-js`.

If you'd like to attach different file types, the best way is to call the `attachments` API from your backend, using an app scoped JWT, then sending the message with the resulting attachment.

I realize this is a fair amount more work, but it's the only safe way to do this currently.

Hope that helps.

**Comment by averyvery** [comment]
Thanks @jugarrit, this is an extremely helpful response. We have our own file endpoint/storage system, so we'll continue uploading to that and sending those as `mediaUrl` with our messages. This solution works for us, I just had a request to make it as fast as it is on iOS, so your explanation of _why_ iOS is so fast is exactly what I wanted to hear. 

Thanks again!
